/*
 * proven.js: which tricks the recogniser has been seen to name when flown.
 *
 * This file is part of the Paraguayan Drone Combat Simulator.
 *
 * The Paraguayan Drone Combat Simulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * The Paraguayan Drone Combat Simulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Paraguayan Drone Combat Simulator. If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * GENERATED by `node scripts/trick-sweep.js --all --write` (npm run
 * trick:proven). Do not edit by hand: rerun and commit after any change to
 * the trick catalogue or the recogniser.
 *
 * Every scoreable pattern is flown from its own step list at three bank
 * angles and three turn errors, nine flights each. RUNS is how many were
 * flown and LANDED how many came out with the pattern's own name, so
 * landed === runs means every flight. The trick list in the UI reads PROVEN
 * and leaves out a trick that never landed.
 *
 * NOT_FLOWN lists the patterns this rig cannot fly yet, with the reason. It
 * is a gap in the evidence, not a verdict on the trick.
 */

export const PROVEN = {
  'Rubik\'s Cube': { runs: 9, landed: 9 },
  'Cubik\'s Rube': { runs: 9, landed: 9 },
  'Vanny Roll': { runs: 9, landed: 9 },
  'Segmented Flips/Rolls': { runs: 9, landed: 9 },
  'Invert Rewind': { runs: 9, landed: 9 },
  'Juicy Flick': { runs: 9, landed: 9 },
  'Snapback': { runs: 9, landed: 9 },
  'Immelmann Turn': { runs: 9, landed: 9 },
  'Powerloop': { runs: 9, landed: 9 },
  'Maverick Loop': { runs: 9, landed: 9 },
  'Split-S': { runs: 9, landed: 3 },
  'Matty Flip': { runs: 9, landed: 9 },
  'Orbit x2': { runs: 9, landed: 9 },
  'Trippy Spin x2': { runs: 9, landed: 9 },
  '1 Trippy Spin': { runs: 9, landed: 9 },
  'Yaw Spin': { runs: 9, landed: 9 },
  'Power Flip': { runs: 9, landed: 9 },
  'Power Roll': { runs: 9, landed: 7 },
  'Inverted 360 Powerloop': { runs: 9, landed: 6 },
  'Blindflip': { runs: 9, landed: 0 },
  'Mavvy Roll': { runs: 9, landed: 9 },
  'Donkey Loop': { runs: 9, landed: 9 },
  'Mavvelmann': { runs: 9, landed: 0 },
  'Anti Matty': { runs: 9, landed: 9 },
  'Power Matty': { runs: 9, landed: 9 },
  'Matty Roll': { runs: 9, landed: 9 },
  'Matty 360': { runs: 9, landed: 6 },
  'Matty Twister': { runs: 9, landed: 0 },
  'Half Matty': { runs: 9, landed: 0 },
  '540 Half Matty': { runs: 9, landed: 0 },
  'Split Yaw': { runs: 9, landed: 6 },
  'Split-Back': { runs: 9, landed: 0 },
  'Inverted Yaw Tracking': { runs: 9, landed: 9 },
  'Eject Roll': { runs: 9, landed: 9 },
  'Stellar Eject Roll': { runs: 9, landed: 0 },
  'True Barani': { runs: 9, landed: 0 },
  'Cinnamon Roll': { runs: 9, landed: 0 },
  'Side Loop': { runs: 9, landed: 0 },
  'Flip Stall Rewind': { runs: 9, landed: 9 },
  '360 Stall Rewind': { runs: 9, landed: 9 },
  'Wall Ride': { runs: 9, landed: 0 },
  'Reverse Wall Ride': { runs: 9, landed: 0 },
  'Double Flip': { runs: 9, landed: 9 },
  'Double Roll': { runs: 9, landed: 9 },
  'Flip': { runs: 9, landed: 9 },
  'Roll': { runs: 9, landed: 9 },
  'Inverted Yaw Spin': { runs: 9, landed: 9 },
};

export const NOT_FLOWN = {
  'Beginner Matty': 'a lap with no turn of its own, which the rig has no way to fly',
  'Power Split': 'a second lap, and this rig plans one lap at a time',
  'Barani': 'a second lap, and this rig plans one lap at a time',
  'Rollani': 'a second lap, and this rig plans one lap at a time',
  'Flipani': 'a second lap, and this rig plans one lap at a time',
  'Mavani': 'a second lap, and this rig plans one lap at a time',
  'Immelloop': 'a second lap, and this rig plans one lap at a time',
  'Immelmatt': 'a second lap, and this rig plans one lap at a time',
  'Jump Rope': 'a lap with no turn of its own, which the rig has no way to fly',
  'Half Mavvy': 'a second lap, and this rig plans one lap at a time',
  'Wall Tap': 'a touch on a solid, and this rig flies in empty air',
  'Roll Tap': 'a touch on a solid, and this rig flies in empty air',
  'Loop Tap': 'a touch on a solid, and this rig flies in empty air',
  'Downtown Tap': 'a touch on a solid, and this rig flies in empty air',
  'Ceiling Tap': 'a touch on a solid, and this rig flies in empty air',
  'Maverick Tap Rewind': 'a touch on a solid, and this rig flies in empty air',
  'Power Switch Tap': 'a touch on a solid, and this rig flies in empty air',
};
