/*
 * itaipu-targets.js: where each war target stands on the Itaipu map, as
 * the map builds it (the dam part's targets and the war part's yard,
 * map.targets): its centre `at` in scene metres (y up) and its reach `r`.
 * GENERATED by scripts/war-targets.js from the built map; do not edit it
 * by hand. `node scripts/war-targets.js --check` fails when this file and
 * the map differ. Mission 1 (missions/itaipu-1.js) adds each target's MW.
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */

export default {
  'intake-0': { at: [-194.353, 187.25, -1827.715], r: 12 },
  'intake-1': { at: [-161.266, 187.25, -1819.863], r: 12 },
  'intake-2': { at: [-128.18, 187.25, -1812.01], r: 12 },
  'intake-3': { at: [-95.093, 187.25, -1804.157], r: 12 },
  'intake-4': { at: [-62.007, 187.25, -1796.305], r: 12 },
  'intake-5': { at: [-28.92, 187.25, -1788.452], r: 12 },
  'intake-6': { at: [4.166, 187.25, -1780.599], r: 12 },
  'intake-7': { at: [37.261, 187.25, -1772.783], r: 12 },
  'intake-8': { at: [70.444, 187.25, -1765.373], r: 12 },
  'intake-9': { at: [103.627, 187.25, -1757.962], r: 12 },
  'intake-10': { at: [136.81, 187.25, -1750.551], r: 12 },
  'intake-11': { at: [169.993, 187.25, -1743.14], r: 12 },
  'intake-12': { at: [203.176, 187.25, -1735.73], r: 12 },
  'intake-13': { at: [236.358, 187.25, -1728.319], r: 12 },
  'intake-14': { at: [269.541, 187.25, -1720.908], r: 12 },
  'intake-15': { at: [302.724, 187.25, -1713.497], r: 12 },
  'intake-16': { at: [335.907, 187.25, -1706.087], r: 12 },
  'intake-17': { at: [369.09, 187.25, -1698.676], r: 12 },
  'intake-18': { at: [402.273, 187.25, -1691.265], r: 12 },
  'intake-19': { at: [435.456, 187.25, -1683.854], r: 12 },
  'gate-0': { at: [-1125.156, 209.83, -959.204], r: 12.5 },
  'gate-1': { at: [-1101.159, 209.83, -967.73], r: 12.5 },
  'gate-2': { at: [-1077.162, 209.83, -976.257], r: 12.5 },
  'gate-3': { at: [-1053.166, 209.83, -984.783], r: 12.5 },
  'gate-4': { at: [-1029.169, 209.83, -993.309], r: 12.5 },
  'gate-5': { at: [-1005.172, 209.83, -1001.835], r: 12.5 },
  'gate-6': { at: [-981.175, 209.83, -1010.362], r: 12.5 },
  'gate-7': { at: [-957.178, 209.83, -1018.888], r: 12.5 },
  'gate-8': { at: [-933.181, 209.83, -1027.414], r: 12.5 },
  'gate-9': { at: [-909.184, 209.83, -1035.941], r: 12.5 },
  'gate-10': { at: [-885.187, 209.83, -1044.467], r: 12.5 },
  'gate-11': { at: [-861.19, 209.83, -1052.993], r: 12.5 },
  'gate-12': { at: [-837.193, 209.83, -1061.519], r: 12.5 },
  'gate-13': { at: [-813.196, 209.83, -1070.046], r: 12.5 },
  'penstock-0': { at: [-214.888, 169.032, -1733.633], r: 8 },
  'penstock-1': { at: [-181.767, 169.04, -1726.127], r: 8 },
  'penstock-2': { at: [-148.552, 169.049, -1718.599], r: 8 },
  'penstock-3': { at: [-115.431, 169.057, -1711.092], r: 8 },
  'penstock-4': { at: [-82.195, 169.066, -1703.559], r: 8 },
  'penstock-5': { at: [-49.075, 169.074, -1696.052], r: 8 },
  'penstock-6': { at: [-15.954, 169.082, -1688.545], r: 8 },
  'penstock-7': { at: [17.261, 169.091, -1681.017], r: 8 },
  'penstock-8': { at: [50.382, 169.099, -1673.509], r: 8 },
  'penstock-9': { at: [83.502, 169.107, -1666.002], r: 8 },
  'penstock-10': { at: [116.717, 169.115, -1658.473], r: 8 },
  'penstock-11': { at: [149.837, 169.123, -1650.965], r: 8 },
  'penstock-12': { at: [183.053, 169.131, -1643.436], r: 8 },
  'penstock-13': { at: [216.173, 169.138, -1635.928], r: 8 },
  'penstock-14': { at: [249.314, 169.146, -1628.415], r: 8 },
  'penstock-15': { at: [282.529, 169.154, -1620.886], r: 8 },
  'penstock-16': { at: [315.649, 169.161, -1613.377], r: 8 },
  'penstock-17': { at: [348.769, 169.169, -1605.869], r: 8 },
  'penstock-18': { at: [381.984, 169.176, -1598.339], r: 8 },
  'penstock-19': { at: [415.104, 169.184, -1590.83], r: 8 },
  'yard-right': { at: [-2145.559, 226.201, -431.874], r: 537 },
};
