/*
 * voicelen.js: GENERATED by scripts/films-time.js from
 * assets/audio/war/manifest.json. Do not edit: npm run films:time.
 *
 * Every war voice line's measured length, seconds, in each language.
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */

export default Object.freeze({
  'bearing-gorge': { en: 2.145, es: 2.735 },
  'bearing-high': { en: 2.345, es: 2.265 },
  'bearing-lines': { en: 2.175, es: 2.205 },
  'bearing-n': { en: 2.785, es: 2.485 },
  'bearing-ne': { en: 1.475, es: 1.545 },
  'bearing-nw': { en: 1.495, es: 2.005 },
  'bearing-river': { en: 2.275, es: 2.205 },
  'bearing-water': { en: 2.415, es: 2.295 },
  'beat-rack': { en: 2.915, es: 3.465 },
  'beat-rack-2': { en: 2.635, es: 2.535 },
  'bird-lost': { en: 3.015, es: 2.895 },
  'brief-itaipu-2-1': { en: 3.755, es: 4.645 },
  'brief-itaipu-2-2': { en: 4.265, es: 4.865 },
  'brief-itaipu-3-1': { en: 4.905, es: 5.825 },
  'brief-itaipu-3-2': { en: 4.095, es: 5.705 },
  'brief-itaipu-4-1': { en: 4.915, es: 5.965 },
  'brief-itaipu-4-2': { en: 3.805, es: 5.245 },
  'debrief-itaipu-1-lose': { en: 2.675, es: 2.735 },
  'debrief-itaipu-1-win': { en: 4.095, es: 5.705 },
  'debrief-itaipu-2-lose': { en: 4.965, es: 4.945 },
  'debrief-itaipu-2-win': { en: 3.345, es: 3.795 },
  'debrief-itaipu-3-lose': { en: 3.415, es: 5.435 },
  'debrief-itaipu-3-win': { en: 3.945, es: 3.905 },
  'debrief-itaipu-4-lose': { en: 4.115, es: 4.895 },
  'debrief-itaipu-4-win': { en: 5.275, es: 5.585 },
  'film-itaipu-1-1': { en: 1.155, es: 1.305 },
  'film-itaipu-1-2': { en: 2.765, es: 3.065 },
  'film-itaipu-1-3': { en: 3.985, es: 4.805 },
  'film-itaipu-1-4': { en: 4.655, es: 4.765 },
  'film-itaipu-1-5': { en: 4.055, es: 4.605 },
  'film-itaipu-1-6': { en: 6.735, es: 4.965 },
  'film-itaipu-1-7': { en: 4.105, es: 3.965 },
  'hit-gate': { en: 2.735, es: 3.655 },
  'hit-intake': { en: 2.295, es: 3.165 },
  'hit-penstock': { en: 3.535, es: 3.685 },
  'hit-yard': { en: 3.255, es: 4.785 },
  'intro-1': { en: 1.125, es: 1.555 },
  'intro-2': { en: 5.625, es: 6.565 },
  'intro-3': { en: 4.155, es: 4.915 },
  'intro-4': { en: 4.295, es: 4.845 },
  'intro-5': { en: 5.475, es: 5.315 },
  'intro-6': { en: 4.665, es: 5.695 },
  'intro-7': { en: 5.095, es: 3.905 },
  'itaipu-1-s0-brief': { en: 4.865, es: 6.025 },
  'itaipu-1-s0-rules': { en: 5.205, es: 5.805 },
  'itaipu-1-s1-down': { en: 3.055, es: 3.115 },
  'itaipu-1-s1-eyes': { en: 3.755, es: 3.615 },
  'itaipu-1-s1-gone': { en: 2.885, es: 2.585 },
  'itaipu-1-s1-why': { en: 4.895, es: 4.535 },
  'itaipu-1-s2-again': { en: 3.065, es: 2.895 },
  'itaipu-1-s2-clear': { en: 2.815, es: 2.695 },
  'itaipu-1-s2-probe': { en: 4.105, es: 4.985 },
  'itaipu-1-s3-clear': { en: 2.425, es: 1.995 },
  'itaipu-1-s3-hold': { en: 4.255, es: 4.725 },
  'itaipu-1-s3-split': { en: 4.795, es: 4.515 },
  'itaipu-1-s5-all': { en: 4.375, es: 4.285 },
  'itaipu-1-s5-order': { en: 4.135, es: 4.105 },
  'itaipu-1-ta-turn': { en: 4.155, es: 3.795 },
  'itaipu-1-ta-why': { en: 5.875, es: 5.295 },
  'itaipu-1-tb-turn': { en: 4.705, es: 4.655 },
  'itaipu-1-tb-why': { en: 4.475, es: 4.605 },
  'itaipu-1-tc-turn': { en: 4.555, es: 4.075 },
  'itaipu-1-tc-why': { en: 3.575, es: 4.825 },
  'jammer-down': { en: 2.755, es: 4.135 },
  'kill-1': { en: 1.315, es: 1.845 },
  'kill-2': { en: 1.895, es: 3.025 },
  'kill-multi': { en: 2.765, es: 2.485 },
  'lose-output': { en: 4.365, es: 5.195 },
  'lose-rack': { en: 3.885, es: 5.135 },
  'output-low': { en: 3.895, es: 3.855 },
  'rack-last': { en: 2.265, es: 2.245 },
  'rack-low': { en: 3.285, es: 4.095 },
  'relay-down': { en: 2.715, es: 3.225 },
  'relay-up': { en: 3.615, es: 3.815 },
  'scouts-down': { en: 2.825, es: 3.455 },
  'signal-back': { en: 2.145, es: 3.185 },
  'signal-lost': { en: 2.495, es: 3.135 },
  'signal-weak': { en: 2.745, es: 2.315 },
  'stage-lost': { en: 2.855, es: 2.905 },
  'start': { en: 5.455, es: 5.755 },
  'wave-boat': { en: 4.735, es: 4.395 },
  'wave-clear': { en: 3.675, es: 4.665 },
  'wave-fpv': { en: 5.415, es: 5.415 },
  'wave-hunter': { en: 5.165, es: 5.695 },
  'wave-jammer': { en: 4.055, es: 5.235 },
  'wave-last': { en: 4.025, es: 3.595 },
  'wave-loiter': { en: 5.115, es: 6.025 },
  'wave-scout': { en: 4.675, es: 5.495 },
  'wave-strike': { en: 4.605, es: 6.305 },
  'win': { en: 5.455, es: 8.125 },
});
