/*
 * films-time.js: the measured length of every war voice line, in both
 * languages, as a module the room and every screen import
 * (src/share/war/voicelen.js), so a film's shots are as long as their
 * lines and the room's briefing is as long as its film
 * (src/share/war/film.js, docs/campaign/INTROS.md section 2).
 * npm run films:time.
 *
 *     node scripts/films-time.js           write it from the manifest
 *     node scripts/films-time.js --check   fail when it is not what the
 *                                          manifest says (checks.yml)
 *
 * The lengths are assets/audio/war/manifest.json's `seconds`, which the
 * voice build measured on each line's audio (tools/voice/build.py) and
 * voice:check holds the files to. A module, not the JSON: the room reads
 * it in Node and in a Worker, with no file access in the second.
 *
 * This file is part of the Paraguayan Drone Combat Simulator.
 *
 * The Paraguayan Drone Combat Simulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * The Paraguayan Drone Combat Simulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Paraguayan Drone Combat Simulator. If not, see <https://www.gnu.org/licenses/>.
 */

import { readFileSync, writeFileSync } from 'node:fs';

const MANIFEST = new URL('../assets/audio/war/manifest.json', import.meta.url);
const OUT = new URL('../src/share/war/voicelen.js', import.meta.url);
const LANGS = ['en', 'es'];

const voice = JSON.parse(readFileSync(MANIFEST, 'utf8')).voice;
const byId = {};
for (const [key, v] of Object.entries(voice)) {
  const dot = key.lastIndexOf('.');
  const id = key.slice(0, dot);
  const lang = key.slice(dot + 1);
  if (!LANGS.includes(lang)) {
    throw new Error(`films-time: ${key} is in no language this knows`);
  }
  (byId[id] ??= {})[lang] = v.seconds;
}
const ids = Object.keys(byId).sort();
const missing = ids.filter((id) => LANGS.some((l) => typeof byId[id][l] !== 'number'));
if (missing.length) {
  throw new Error(`films-time: no length in every language for ${missing.join(', ')}`);
}
const rows = ids.map((id) => `  '${id}': { en: ${byId[id].en}, es: ${byId[id].es} },`).join('\n');
const text = `/*
 * voicelen.js: GENERATED by scripts/films-time.js from
 * assets/audio/war/manifest.json. Do not edit: npm run films:time.
 *
 * Every war voice line's measured length, seconds, in each language.
 *
 * This file is part of the Paraguayan Drone Combat Simulator.
 *
 * The Paraguayan Drone Combat Simulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * The Paraguayan Drone Combat Simulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Paraguayan Drone Combat Simulator. If not, see <https://www.gnu.org/licenses/>.
 */

export default Object.freeze({
${rows}
});
`;

if (process.argv.includes('--check')) {
  let had = '';
  try {
    had = readFileSync(OUT, 'utf8');
  } catch {
    had = '';
  }
  if (had !== text) {
    console.log('films:time FAIL: src/share/war/voicelen.js is not what the manifest says; run npm run films:time');
    process.exit(1);
  }
  console.log(`films:time ok: ${ids.length} lines, the module matches the manifest`);
} else {
  writeFileSync(OUT, text);
  console.log(`films:time wrote ${ids.length} lines to src/share/war/voicelen.js`);
}
