/*
 * hulls-gen.js: write configs/hulls.js, every airframe's crash part boxes,
 * read out of the built module (dist/sim.wasm) through sim_part_info, so
 * the rooms' mid air referee (src/game/midair.js, edge/rooms/referee.js),
 * which has no WASM, judges contact against the very boxes the crash
 * physics breaks. docs/MULTIPLAYER-PLAN.md section 6.2.
 *
 *   node scripts/hulls-gen.js           write configs/hulls.js
 *   node scripts/hulls-gen.js --check   fail if configs/hulls.js is not
 *                                       what the built module says
 *                                       (npm run hulls:check, in CI)
 *
 * The same pattern as lint:catalog: the generated file is committed, and
 * the check holds it to its source. A part table change in
 * src/native/crash_parts.h that is built into dist/sim.wasm without
 * running this fails the check.
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadSim, SIM_OK } from '../tests/lib/simmod.js';
import { AIRFRAMES } from '../configs/airframes.js';
import { MATERIALS, PART_KINDS } from '../configs/parts.js';
import { readPartTable } from './lib/crash.js';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = join(root, 'configs', 'hulls.js');
const check = process.argv.includes('--check');

const HEADER = `/*
 * hulls.js: every airframe's crash part boxes, GENERATED by
 * scripts/hulls-gen.js from dist/sim.wasm (sim_part_info). Do not edit:
 * change src/native/crash_parts.h, build, and run the script.
 * npm run hulls:check holds this file to the built module.
 *
 * What the rooms' mid air referee (src/game/midair.js) meets another
 * aircraft with: per airframe id (configs/airframes.js), its all up mass
 * in kg (the part masses' sum, which is the plant's mass) and its parts in
 * table order, each with its kind and material (configs/parts.js
 * PART_KINDS, MATERIALS) and its hull's bounding box, body frame, plant
 * metres (x forward, y left, z up, origin at the CG). The whoop's are the
 * scaled table the shell flies it with (sim_set_part_table 1).
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */
`;

/* The whoop is the five inch's plant with the real whoop's parts scaled
 * to the world it flies in (src/main.js syncPartTable). */
const PART_TABLE_FOR = { whoop65: 1 };

const must = (code, what) => {
  if (code !== SIM_OK) {
    throw new Error(`${what} returned ${code}`);
  }
};

const wasm = await readFile(join(root, 'dist', 'sim.wasm'));
const config = await readFile(join(root, 'configs', 'betaflight-default.diff'), 'utf8');
const sim = await loadSim(wasm);
must(sim.init(config), 'sim_init');

const lines = [HEADER, 'export const HULLS = {'];
for (const af of AIRFRAMES) {
  must(sim.e.sim_set_airframe(af.simId), `sim_set_airframe(${af.simId})`);
  must(sim.e.sim_set_part_table(PART_TABLE_FOR[af.id] ?? 0), 'sim_set_part_table');
  must(sim.reset(), 'sim_reset');
  const table = readPartTable(sim);
  if (!table.length) {
    throw new Error(`${af.id}: the module has no part table`);
  }
  const mass = table.reduce((m, p) => m + p.mass, 0);
  lines.push(`  '${af.id}': {`);
  lines.push(`    mass: ${mass},`);
  lines.push('    parts: [');
  for (const p of table) {
    lines.push(`      { kind: '${PART_KINDS[p.kind]}', mat: '${MATERIALS[p.material]}', min: [${p.boxMin.join(', ')}], max: [${p.boxMax.join(', ')}] },`);
  }
  lines.push('    ],');
  lines.push('  },');
}
lines.push('};', '');
const text = lines.join('\n');

if (check) {
  let have = '';
  try {
    have = await readFile(OUT, 'utf8');
  } catch (e) {
    have = '';
  }
  if (have !== text) {
    console.log('hulls:check FAIL: configs/hulls.js is not what dist/sim.wasm says. Run node scripts/hulls-gen.js.');
    process.exit(1);
  }
  console.log(`hulls:check pass: ${AIRFRAMES.length} airframes, configs/hulls.js matches dist/sim.wasm`);
} else {
  await writeFile(OUT, text);
  console.log(`wrote ${OUT}: ${AIRFRAMES.length} airframes`);
}
