/*
 * war-targets.js: the Itaipu map's war targets as data, for mission 1
 * (docs/WARFARE-PLAN.md sections 4.2 and 8). The room has no map, so the
 * mission (src/share/war/missions/itaipu-1.js) cannot ask map.targets
 * where an intake is: this builds the map in headless Chromium, the dam
 * part's targets and the war part's yard as the shell has them, and
 * writes each one's centre and reach into src/share/war/itaipu-targets.js,
 * which the mission imports.
 *
 * And for the same reason the power lines an attacker can fly into
 * (src/share/war/wires.js): the town part's wire chords as drawn, those
 * of every span within CORRIDOR_M in plan of where some attacker of some
 * mission flies (every wave at one to eight pilots, every attacker of it
 * at no error and both ends of its spread), into
 * src/share/war/itaipu-wires.js.
 *
 *   node scripts/war-targets.js           write the modules
 *   node scripts/war-targets.js --check   exit 1 if a written one differs
 *                                         from the map as built now
 *
 * Run it by hand after the map's targets move (the dam part or the yard),
 * its lines move or a mission's routes change, and commit its output with
 * the change. It needs the Itaipu data folder
 * (FDFPV_ITAIPU_DATA, by default ~/Desktop/fdfpv-itaipu-data), so it is a
 * local check, not a CI one.
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { openPage } from '../tests/lib/page.js';
import { SETTINGS_KEY } from '../src/ui/ui.js';
import { planAgent, poseAt } from '../src/share/war/routes.js';
import { MISSIONS, waveSize, waveTarget } from '../src/share/war/missions/index.js';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = join(root, 'src', 'share', 'war', 'itaipu-targets.js');
const OUT_WIRES = join(root, 'src', 'share', 'war', 'itaipu-wires.js');
/* A span is kept when a chord of it lies this near, in plan, to where an
 * attacker flies: past the widest a formation and an error spread it. */
const CORRIDOR_M = 150;

/* Every id mission 1 may aim at, in the order written. */
const IDS = [
  ...Array.from({ length: 20 }, (_, k) => `intake-${k}`),
  ...Array.from({ length: 14 }, (_, k) => `gate-${k}`),
  ...Array.from({ length: 20 }, (_, k) => `penstock-${k}`),
  'yard-right',
];

const HEADER = `/*
 * itaipu-targets.js: where each war target stands on the Itaipu map, as
 * the map builds it (the dam part's targets and the war part's yard,
 * map.targets): its centre \`at\` in scene metres (y up) and its reach \`r\`.
 * GENERATED by scripts/war-targets.js from the built map; do not edit it
 * by hand. \`node scripts/war-targets.js --check\` fails when this file and
 * the map differ. Mission 1 (missions/itaipu-1.js) adds each target's MW.
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */
`;

/* Millimetres, as the wire rounds a point. */
const mm = (v) => Math.round(v * 1000) / 1000;

function render(targets) {
  const lines = IDS.map((id) => {
    const t = targets[id];
    return `  '${id}': { at: [${t.at.map(mm).join(', ')}], r: ${mm(t.r)} },`;
  });
  return `${HEADER}\nexport default {\n${lines.join('\n')}\n};\n`;
}

const WIRES_HEADER = `/*
 * itaipu-wires.js: the power lines a scripted attacker can fly into on the
 * Itaipu map (src/share/war/wires.js): every span within ${CORRIDOR_M} m in plan
 * of where an attacker of some mission flies, as [span, then its
 * conductors' and earth wire's chords, ax, ay, az, bx, by, bz each], scene
 * metres (y up), to the centimetre. GENERATED by scripts/war-targets.js
 * from the built map (src/maps/itaipu/town/power.js); do not edit it by
 * hand. \`node scripts/war-targets.js --check\` fails when this file and
 * the map or the missions' routes differ.
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */
`;

/* The cells of a CORRIDOR_M grid some attacker flies over. */
function corridor() {
  const cells = new Set();
  for (const m of Object.values(MISSIONS)) {
    if (m.map !== 'itaipu') {
      continue;
    }
    for (const w of m.waves) {
      if (w.kind === 'hunter') {
        continue;
      }
      for (let pilots = 1; pilots <= 8; pilots += 1) {
        const n = waveSize(w, pilots);
        for (let k = 0; k < n; k += 1) {
          for (const err of w.spread ? [-w.spread, 0, w.spread] : [0]) {
            const plan = planAgent(m, {
              id: 1, kind: w.kind, route: w.route, t0: 0, k, n, err, target: waveTarget(w, k),
            });
            const end = Number.isFinite(plan.tEnd) ? plan.tEnd : plan.phases[plan.phases.length - 1].t1;
            for (let t = 0; t <= end; t += 250) {
              const p = poseAt(plan, t).p;
              cells.add(`${Math.floor(p[0] / CORRIDOR_M)},${Math.floor(p[2] / CORRIDOR_M)}`);
            }
          }
        }
      }
    }
  }
  return cells;
}

/* The chords (layOut's, [ax, ay, az, bx, by, bz, r, k, hx, hz, span]) of
 * every span in the corridor, as the module's text. */
function renderWires(chords) {
  const cells = corridor();
  const near = (x, z) => {
    const i = Math.floor(x / CORRIDOR_M);
    const j = Math.floor(z / CORRIDOR_M);
    for (let a = -1; a <= 1; a += 1) {
      for (let b = -1; b <= 1; b += 1) {
        if (cells.has(`${i + a},${j + b}`)) {
          return true;
        }
      }
    }
    return false;
  };
  const kept = new Set(chords.filter((w) => near(w[0], w[2]) || near(w[3], w[5])).map((w) => w[10]));
  const spans = new Map();
  for (const w of chords) {
    if (!kept.has(w[10])) {
      continue;
    }
    if (!spans.has(w[10])) {
      spans.set(w[10], []);
    }
    spans.get(w[10]).push(...w.slice(0, 6).map(cm));
  }
  const rows = [...spans.entries()].sort((a, b) => a[0] - b[0]).map(([span, flat]) => `    [${span}, ${flat.join(', ')}],`);
  return `${WIRES_HEADER}\nexport default {\n  spans: [\n${rows.join('\n')}\n  ],\n};\n`;
}

/* Centimetres, as the wires are written. */
const cm = (v) => Math.round(v * 100) / 100;

async function readMap() {
  const settings = {
    airframe: '5inch', airframeAsked: true, map: 'itaipu', graphics: 'low', graphicsAuto: false, sound: false,
  };
  const seed = [`try {
    const k = ${JSON.stringify(SETTINGS_KEY)};
    const s = JSON.parse(localStorage.getItem(k) || '{}');
    Object.assign(s, ${JSON.stringify(settings)});
    localStorage.setItem(k, JSON.stringify(s));
    localStorage.setItem('webfpv.airhint.v2', '1');
    localStorage.setItem('webfpv.stats.v1', JSON.stringify({ optOut: true }));
  } catch (e) { /* Storage refused; the run boots on its defaults. */ }`];
  const page = await openPage({
    root, width: 640, height: 360, url: '/index.html?map=itaipu', seed,
  });
  try {
    await page.until('window.__shellReady && window.__map && window.__map().ready && window.__map().id === "itaipu"', 300000);
    await page.evaluate('window.__drawOff(true)');
    const json = await page.evaluate(`JSON.stringify(Object.fromEntries(Object.entries(window.__mapScene().userData.itaipu.targets)
      .map(([id, t]) => [id, { at: t.at, r: t.r }])))`);
    const wires = await page.evaluate('JSON.stringify(window.__mapScene().userData.itaipu.parts.town.town.wires)');
    return { targets: JSON.parse(json), wires: JSON.parse(wires) };
  } finally {
    await page.close();
  }
}

async function main() {
  const check = process.argv.includes('--check');
  const { targets, wires } = await readMap();
  const missing = IDS.filter((id) => !targets[id]);
  if (missing.length) {
    throw new Error(`the built map has no ${missing.join(', ')}`);
  }
  const extra = Object.keys(targets).filter((id) => !IDS.includes(id));
  if (extra.length) {
    throw new Error(`the built map has targets this script does not write: ${extra.join(', ')}`);
  }
  const outputs = [
    { path: OUT, text: render(targets), what: `${IDS.length} targets` },
    { path: OUT_WIRES, text: renderWires(wires), what: 'power lines in the attackers\' way' },
  ];
  if (!check) {
    for (const o of outputs) {
      await writeFile(o.path, o.text);
      console.log(`wrote ${o.what} to ${o.path}`);
    }
    return;
  }
  for (const o of outputs) {
    const had = await readFile(o.path, 'utf8').catch(() => '');
    if (had !== o.text) {
      const a = had.split('\n');
      const b = o.text.split('\n');
      const diff = b.map((l, i) => (l !== a[i] ? `  map:  ${l.trim().slice(0, 160)}\n  file: ${(a[i] ?? '').trim().slice(0, 160)}` : null)).filter(Boolean);
      console.error(`FAIL, ${o.path} differs from the built map; run node scripts/war-targets.js and commit it\n${diff.slice(0, 8).join('\n')}`);
      process.exitCode = 1;
      continue;
    }
    console.log(`PASS, the ${o.what} in ${o.path} are the built map's`);
  }
}

main().catch((e) => {
  console.error(e && e.stack ? e.stack : e);
  process.exitCode = 1;
});
