/*
 * war-targets.js: the Itaipu map's war targets as data, for mission 1
 * (docs/WARFARE-PLAN.md sections 4.2 and 8). The room has no map, so the
 * mission (src/share/war/missions/itaipu-1.js) cannot ask map.targets
 * where an intake is: this builds the map in headless Chromium, the dam
 * part's targets and the war part's yard as the shell has them, and
 * writes each one's centre and reach into src/share/war/itaipu-targets.js,
 * which the mission imports.
 *
 *   node scripts/war-targets.js           write the module
 *   node scripts/war-targets.js --check   exit 1 if the written one differs
 *                                         from the map as built now
 *
 * Run it by hand after the map's targets move (the dam part or the yard),
 * and commit its output with the change. It needs the Itaipu data folder
 * (FDFPV_ITAIPU_DATA, by default ~/Desktop/fdfpv-itaipu-data), so it is a
 * local check, not a CI one.
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { openPage } from '../tests/lib/page.js';
import { SETTINGS_KEY } from '../src/ui/ui.js';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = join(root, 'src', 'share', 'war', 'itaipu-targets.js');

/* Every id mission 1 may aim at, in the order written. */
const IDS = [
  ...Array.from({ length: 20 }, (_, k) => `intake-${k}`),
  ...Array.from({ length: 14 }, (_, k) => `gate-${k}`),
  ...Array.from({ length: 20 }, (_, k) => `penstock-${k}`),
  'yard-right',
];

const HEADER = `/*
 * itaipu-targets.js: where each war target stands on the Itaipu map, as
 * the map builds it (the dam part's targets and the war part's yard,
 * map.targets): its centre \`at\` in scene metres (y up) and its reach \`r\`.
 * GENERATED by scripts/war-targets.js from the built map; do not edit it
 * by hand. \`node scripts/war-targets.js --check\` fails when this file and
 * the map differ. Mission 1 (missions/itaipu-1.js) adds each target's MW.
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */
`;

/* Millimetres, as the wire rounds a point. */
const mm = (v) => Math.round(v * 1000) / 1000;

function render(targets) {
  const lines = IDS.map((id) => {
    const t = targets[id];
    return `  '${id}': { at: [${t.at.map(mm).join(', ')}], r: ${mm(t.r)} },`;
  });
  return `${HEADER}\nexport default {\n${lines.join('\n')}\n};\n`;
}

async function readMap() {
  const settings = {
    airframe: '5inch', airframeAsked: true, map: 'itaipu', graphics: 'low', graphicsAuto: false, sound: false,
  };
  const seed = [`try {
    const k = ${JSON.stringify(SETTINGS_KEY)};
    const s = JSON.parse(localStorage.getItem(k) || '{}');
    Object.assign(s, ${JSON.stringify(settings)});
    localStorage.setItem(k, JSON.stringify(s));
    localStorage.setItem('webfpv.airhint.v2', '1');
    localStorage.setItem('webfpv.stats.v1', JSON.stringify({ optOut: true }));
  } catch (e) { /* Storage refused; the run boots on its defaults. */ }`];
  const page = await openPage({
    root, width: 640, height: 360, url: '/index.html?map=itaipu', seed,
  });
  try {
    await page.until('window.__shellReady && window.__map && window.__map().ready && window.__map().id === "itaipu"', 300000);
    await page.evaluate('window.__drawOff(true)');
    const json = await page.evaluate(`JSON.stringify(Object.fromEntries(Object.entries(window.__mapScene().userData.itaipu.targets)
      .map(([id, t]) => [id, { at: t.at, r: t.r }])))`);
    return JSON.parse(json);
  } finally {
    await page.close();
  }
}

async function main() {
  const check = process.argv.includes('--check');
  const targets = await readMap();
  const missing = IDS.filter((id) => !targets[id]);
  if (missing.length) {
    throw new Error(`the built map has no ${missing.join(', ')}`);
  }
  const extra = Object.keys(targets).filter((id) => !IDS.includes(id));
  if (extra.length) {
    throw new Error(`the built map has targets this script does not write: ${extra.join(', ')}`);
  }
  const text = render(targets);
  if (!check) {
    await writeFile(OUT, text);
    console.log(`wrote ${IDS.length} targets to ${OUT}`);
    return;
  }
  const had = await readFile(OUT, 'utf8').catch(() => '');
  if (had !== text) {
    const a = had.split('\n');
    const b = text.split('\n');
    const diff = b.map((l, i) => (l !== a[i] ? `  map:  ${l.trim()}\n  file: ${(a[i] ?? '').trim()}` : null)).filter(Boolean);
    console.error(`FAIL, ${OUT} differs from the built map; run node scripts/war-targets.js and commit it\n${diff.slice(0, 8).join('\n')}`);
    process.exitCode = 1;
    return;
  }
  console.log(`PASS, the ${IDS.length} targets in src/share/war/itaipu-targets.js are the built map's`);
}

main().catch((e) => {
  console.error(e && e.stack ? e.stack : e);
  process.exitCode = 1;
});
